package com.sztouyun.advertisingsystem.repository.adProfitShare;

import com.sztouyun.advertisingsystem.model.adProfitShare.AdvertisementStoreProfitPeriodStatistic;
import com.sztouyun.advertisingsystem.repository.BaseRepository;

public interface AdvertisementStoreProfitPeriodStatisticRepository extends BaseRepository<AdvertisementStoreProfitPeriodStatistic> {

}
